Data:

Pipeline:
    name: ijepa
    id:

Training_Dynamics:
    batch_size: 24
    epochs: 800
    val_every_n_epoch: 50
    accumulate_grad_batches: 2
    mask:
        mask_strategy: 'random'
        mask_ratio: 0.5
    optimizer:
        name: 'adamw'
        lr: 0.0005
        warmup_epochs: 20
        start_factor: 0.1
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.05
        eta_min: 0.00001

Logging:
    project: 'PlantVillage'
    entity: 'wwy'
    checkpoint_path: 'CHECKPOINTS'
    save_every_n_epoch: 50
    num_samples: 0

device: [0,1,2,3,4,5,6,7]